version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      DB_HOST: postgres
    volumes:
      - ./src:/var/lib/postgresql/data3
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped
    networks:
      - node

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: bd/Dockerfile
    env_file:
      - .env
    ports:
      - '${PG_PORT}:${PG_PORT}'
    volumes:
      - dbdata:/var/lib/postgresql/data3
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    restart: unless-stopped
    networks:
      - node
networks:
    node: 
      driver: bridge
volumes:
  dbdata: